[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Bamurai"
version = "0.1.0"
description = "A package for efficient BAM fragmentation."
authors = [{ name = "Your Name", email = "your.email@example.com" }]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "pysam",
]

[project.optional-dependencies]
dev = ["pytest", "black", "mypy"]

[project.scripts]
bamurai = "bamurai.cli:main"

[tool.setuptools]
packages = ["bamurai"]